version: '3.4'

services:
  catalogdb:
    container_name: eshop_catalogdb
    restart: always
    ports:
        - "27018:27017"
    volumes:
        - mongo_data:/data/db

  basketdb:
    container_name: eshop_basketdb
    restart: always
    ports:
        - "6380:6379"

  discountdb:
    container_name: eshop_discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
        - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: eshop_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
        - "5051:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  portainer:
    container_name: eshop_portainer
    restart: always
    ports:
        - "8088:8000"
        - "9001:9000"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data
    

  catalog.api:
    container_name: eshop_catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27018"
    depends_on:
      - catalogdb
    ports:
      - "7000:80"

  basket.api:
    container_name: eshop_basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6380"
    depends_on:
      - basketdb
    ports:
      - "7001:80"

  discount.api:
    container_name: eshop_discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
    depends_on:
      - discountdb
    ports:
      - "7002:80"

